[project]
name = "mistral"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "streamlit",
    "llama-index==0.9.48",
    "langchain",
    "langchain_community",
    "sentence-transformers",
    "setuptools",
    "huggingface-hub",
    "python-dotenv>=1.1.1",
]
